# Generated by Django 3.2.6 on 2021-10-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211020_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='toy',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
