# Generated by Django 3.2.6 on 2021-10-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_frog_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frog',
            old_name='toy',
            new_name='toys',
        ),
    ]
